name: Site timezone configuration
type: module
description: 'Used to display custom site location and timezone to user.'
package: Custom
version: 1.0
core_version_requirement: ^8 || ^9
dependencies:
  - drupal:block
configure: spec_timezone_site_config.specbee_config
